[package]
name = "zed-vala"
version = "0.1.0"
edition = "2021"
publish = false
license = "LGPL-3.0-or-later"

[lib]
path = "src/vala.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
